<a href="https://colab.research.google.com/github/realBagher/NLP-using-Transformers/blob/main/Models-and-Tokenizers/ModelsUndTokenizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 16.1 MB/s 
     |████████████████████████████████| 596 kB 61.5 MB/s 
     |████████████████████████████████| 6.6 MB 50.3 MB/s 
     |████████████████████████████████| 101 kB 12.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import AutoTokenizer

In [48]:
API_TOKEN = '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'

In [6]:

from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

model = AutoModelForMaskedLM.from_pretrained("bert-base-uncased")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [8]:
tokenizer

PreTrainedTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_len=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [9]:
tokenizer("hello world")

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [10]:
tokens = tokenizer.tokenize("hello world")
tokens

['hello', 'world']

In [12]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[7592, 2088]

In [13]:
tokenizer.convert_ids_to_tokens(ids)

['hello', 'world']

In [14]:
tokenizer.decode(ids)

'hello world'

In [16]:
ids = tokenizer.encode('hello world')
ids

[101, 7592, 2088, 102]

In [17]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [18]:
tokenizer.decode(ids)

'[CLS] hello world [SEP]'

In [19]:
model_inputs = tokenizer('hello world')
model_inputs

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [21]:
data = [
    'i like data',
    'also i hate my life'
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 2951, 102], [101, 2036, 1045, 5223, 2026, 2166, 102]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [22]:
from transformers import AutoModelForSequenceClassification

In [30]:
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased",use_auth_token=API_TOKEN)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [33]:
model_inputs = tokenizer('hello world',return_tensors='pt')

In [35]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput([('logits',
                           tensor([[0.0771, 0.2330]], grad_fn=<AddmmBackward0>))])

In [36]:
outputs.logits

tensor([[0.0771, 0.2330]], grad_fn=<AddmmBackward0>)

In [37]:
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased",use_auth_token=API_TOKEN,num_labels=3)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [38]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput([('logits',
                           tensor([[ 0.2558, -0.7326,  0.1464]], grad_fn=<AddmmBackward0>))])

In [39]:
outputs.logits

tensor([[ 0.2558, -0.7326,  0.1464]], grad_fn=<AddmmBackward0>)

In [40]:
outputs['logits']

tensor([[ 0.2558, -0.7326,  0.1464]], grad_fn=<AddmmBackward0>)

In [41]:
outputs[0]

tensor([[ 0.2558, -0.7326,  0.1464]], grad_fn=<AddmmBackward0>)

In [43]:
outputs.logits.detach().cpu().numpy()

array([[ 0.25575057, -0.73261875,  0.14639121]], dtype=float32)

In [44]:
data = [
    'i like data',
    'also i hate my life'
]
model_inputs=tokenizer(data,padding=True,truncation=True,return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 2951,  102,    0,    0],
        [ 101, 2036, 1045, 5223, 2026, 2166,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1]])}

In [45]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 2951,  102,    0,    0],
        [ 101, 2036, 1045, 5223, 2026, 2166,  102]])

In [46]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1]])

In [47]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput([('logits', tensor([[ 0.2145, -0.6715, -0.2020],
                                   [ 0.1613, -0.7782, -0.0971]], grad_fn=<AddmmBackward0>))])